### PR TITLE
Just some house keeping on the test files, and adjusted the value che…

### PR DESCRIPTION
**Pull request by twozach2**
…cking

### CODE REVIEW

**Comment by twozach2** [comment]
Just made a change to the test loan amount class so that it would check for not only a positve number, but that it was within the range of allowed input.

**Review by natalinamateaki — APPROVED** [review]
Looks great!

**Review by tannershimanek — COMMENTED** [review]
looks good to me

**Review by tannershimanek — COMMENTED** [review]
looks good to me

**Pull request merged**
